# /etc/pacman.conf — AcreetionOS Edition (standard Arch mirrors)
[options]
IgnorePkg = v4l2loopback-dkms
NoUpgrade = pacman
Architecture = auto
Color
CheckSpace
ParallelDownloads = 25
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional
DownloadUser = root

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
